database: mysql


logging:
  level:
    ROOT: ERROR
    com.htmedia: ERROR
    com.htmedia.entity: DEBUG
  file:
    name :  dms-application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


server: 
  port: 8081
  servlet: 
    context-path: /backend
  compression:
    enabled: false
    
  
spring:
  profiles:
    active: local
  application:
    name: backend
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
   
---
    
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/backend?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true        
  sql:
    init:
      continue-on-error: true
      mode: always
    
    
